//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MyCondition.cpp
//  @ Date : 2015/4/10
//  @ Author : 
//
//


#include "MyCondition.h"




MyCondition::MyCondition(pthread_cond_t cond,pthread_mutex_t& mutex) {
	m_mutex = mutex ; 
	m_cond = cond ;
	pthread_cond_init(&m_cond, NULL); 
}

void MyCondition::Wait() {
	pthread_cond_wait(&m_cond, &m_mutex);
}

void MyCondition::Broadscast() {
	pthread_cond_broadcast(&m_cond) ;
}

