//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : MyLock.cpp
//  @ Date : 2015/4/10
//  @ Author : 
//
//


#include "MyLock.h"

MyLock::MyLock(pthread_mutex_t& mutex):m_mutex(mutex){
	pthread_mutex_init(&m_mutex, NULL); 
}

void MyLock::Lock() {
	pthread_mutex_lock(&m_mutex); 
}

void MyLock::Unlock() {
	pthread_mutex_unlock(&m_mutex); 
}


